Homework 4 (Thread pull)
SmirnovMihail/afina pull request #4
Opened 2020-12-05 13:27 UTC by SmirnovMihail

2020-12-06 10:02 UTC, blumix requested changes

2020-12-06 10:02 UTC, blumix commented on include/afina/concurrency/Executor.h
> +            state = State :: kStopped;
если await == false то kStopped никогда не проставится.

2020-12-06 10:02 UTC, blumix commented on include/afina/concurrency/Executor.h
> +        cv_empty.notify_all();
если был создан поток во время исполнения этой функции, не обязательно будить всех остальных

2020-12-06 10:02 UTC, blumix commented on include/afina/concurrency/Executor.h
> +            cv_full.wait(lock);
можно просто не принимать новые задачи если тредпул переполнен

2020-12-06 10:02 UTC, blumix commented on include/afina/concurrency/Executor.h
> +                        executor->existing_workers.load() > executor->max_workers)
min workers?

2020-12-06 10:02 UTC, blumix commented on include/afina/concurrency/Executor.h
> +                    auto res = executor->cv_empty.wait_for(lock,
wait_untill

2020-12-06 10:02 UTC, blumix commented on include/afina/concurrency/Executor.h
> +            task();
try

2020-12-06 16:14 UTC, blumix requested changes

2020-12-06 16:14 UTC, blumix commented on include/afina/concurrency/Executor.h
> +                    auto now = std::chrono::system_clock::now();
засекаешь все равно заново каждый раз

2020-12-06 16:14 UTC, blumix commented on include/afina/concurrency/Executor.h
> +                        executor->cv_finished.notify_all();
тут тоже нужен kStopped

2021-01-06 00:39 UTC, SmirnovMihail commented
Thread pool realization of mt_blocking

2021-01-06 00:39 UTC, merged